services:
  lucee:
    build: .
    image: lucee-mcp:latest
    environment:
      - LUCEE_ADMIN_PASSWORD=qwerty
    ports:
      - "8856:8080" # PORT (Cloud Run compatible)

# docker compose up -d --build
